# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        platform_admin_user_provider:
            id: sylius.admin_user_provider.email_or_name_based

    encoders:
        Sylius\Component\User\Model\UserInterface: sha512

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            logout_on_user_change: true
            switch_user: true
            context: admin
            pattern: ^/admin
            provider: platform_admin_user_provider
            form_login:
                login_path: admin_platform_admin_login
                check_path: admin_platform_admin_login_check
                failure_path: admin_platform_admin_login
                default_target_path: admin_platform_admin_dashboard_index
                use_forward: false
                use_referer: true
#                csrf_token_generator: security.csrf.token_manager
#                csrf_parameter: _csrf_admin_security_token
#                csrf_token_id: admin_authenticate
            remember_me:
                secret: "%secret%"
                path: /admin
                name: APP_ADMIN_REMEMBER_ME
                lifetime: 31536000
                remember_me_parameter: _remember_me
            logout:
                path: admin_platform_admin_logout
                target: admin_platform_admin_login
            anonymous: true

        main:
            logout_on_user_change: true
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        - { path: ^/admin/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login-check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/admin.*", role: ROLE_ADMINISTRATION_ACCESS }
